export const AVAGOTCHI_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_AVAGOTCHI_CONTRACT_ADDRESS || "";
export const FLIPCOIN_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_FLIPCOIN_CONTRACT_ADDRESS || "";
export const TAMAGOTCHI_CONTRACT_ADDRESS = AVAGOTCHI_CONTRACT_ADDRESS || FLIPCOIN_CONTRACT_ADDRESS;
