export const TAMAGOTCHI_ABI = [
  "constructor()",
  "event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)",
  "event ApprovalForAll(address indexed owner, address indexed operator, bool approved)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "event PetInteracted(uint256 indexed tokenId, string action, uint256 hunger, uint256 happiness, uint256 cleanliness)",
  "event PetMinted(uint256 indexed tokenId, string name, address indexed owner)",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
  "function approve(address to, uint256 tokenId)",
  "function balanceOf(address owner) view returns (uint256)",
  "function clean(uint256 _tokenId)",
  "function cleanlinessDecayRate() view returns (uint256)",
  "function feed(uint256 _tokenId)",
  "function getApproved(uint256 tokenId) view returns (address)",
  "function getPetStats(uint256 _tokenId) view returns (uint256 hunger, uint256 happiness, uint256 cleanliness, uint256 health)",
  "function happinessDecayRate() view returns (uint256)",
  "function hungerDecayRate() view returns (uint256)",
  "function isApprovedForAll(address owner, address operator) view returns (bool)",
  "function mint(string _name)",
  "function name() view returns (string)",
  "function nextTokenId() view returns (uint256)",
  "function owner() view returns (address)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function pets(uint256) view returns (string name, uint256 hunger, uint256 happiness, uint256 cleanliness, uint256 health, uint256 lastInteraction, uint256 birthTime)",
  "function play(uint256 _tokenId)",
  "function renounceOwnership()",
  "function safeTransferFrom(address from, address to, uint256 tokenId)",
  "function safeTransferFrom(address from, address to, uint256 tokenId, bytes data)",
  "function setApprovalForAll(address operator, bool approved)",
  "function setDecayRates(uint256 _hunger, uint256 _happiness, uint256 _cleanliness)",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)",
  "function symbol() view returns (string)",
  "function tokenByIndex(uint256 index) view returns (uint256)",
  "function tokenOfOwnerByIndex(address owner, uint256 index) view returns (uint256)",
  "function totalSupply() view returns (uint256)",
  "function transferFrom(address from, address to, uint256 tokenId)"
];
